
pipeline{
	agent any
	stages{
		stage('Build'){
			steps{
				sh "javac sample/Hello.java"
			}
		}
		stage('Run'){
			steps{
				sh "java -cp sample Hello"
			}
		}

	}
	post{
			success{
			echo "This is a java Example"
				echo "================================Build is Successful======================================"
				echo "-------------------------------Trigger using post-commit-------------------------------"
			}
		}
}